<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>manfred.end</groupId>
    <artifactId>exercises-design</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <!-- Design Patterns -->
        <module>design-patterns</module>

        <!-- Architecture Patterns -->
        <module>arch-patterns</module>

        <!-- Domain Modeling -->
        <module>domain-modeling</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <junit4.version>4.13.1</junit4.version>
        <mockito.version>2.23.0</mockito.version>
        <polygene.version>3.0.0</polygene.version>
        <asm.version>5.2</asm.version>
        <johnzon.version>1.1.1</johnzon.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit4.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <!-- Polygene DCI framework -->
            <dependency>
                <groupId>org.apache.polygene.core</groupId>
                <artifactId>org.apache.polygene.core.api</artifactId>
                <version>${polygene.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.polygene.core</groupId>
                <artifactId>org.apache.polygene.core.runtime</artifactId>
                <version>${polygene.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.polygene.core</groupId>
                <artifactId>org.apache.polygene.core.testsupport</artifactId>
                <version>${polygene.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.polygene.libraries</groupId>
                <artifactId>org.apache.polygene.library.constraints</artifactId>
                <version>${polygene.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>${asm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm-util</artifactId>
                <version>${asm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm-commons</artifactId>
                <version>${asm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.johnzon</groupId>
                <artifactId>johnzon-core</artifactId>
                <version>${johnzon.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
